repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        exclude: &exclude_patterns |
            (?x)^.*\.pdb$
            |^scripts/.*$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: *exclude_patterns
      - id: end-of-file-fixer
        exclude: *exclude_patterns
      - id: check-yaml
        exclude: *exclude_patterns
      - id: check-json
        exclude: *exclude_patterns
      - id: check-added-large-files
        exclude: *exclude_patterns
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
        exclude: *exclude_patterns

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: ["--fix", "--line-length", "120"]
        exclude: *exclude_patterns
      - id: ruff-format
        args: ["--line-length", "120"]
        exclude: *exclude_patterns
